  # (use "git restore --staged <file>..." to unstage)
	git restore --staged     src/main/resources/static/appcss/animate.css
	git restore --staged     src/main/resources/static/appcss/bootstrap-grid.css
	git restore --staged     src/main/resources/static/appcss/bootstrap-grid.css.map
	git restore --staged     src/main/resources/static/appcss/bootstrap-grid.min.css
	git restore --staged     src/main/resources/static/appcss/bootstrap-grid.min.css.map
	git restore --staged     src/main/resources/static/appcss/bootstrap-reboot.css
	git restore --staged     src/main/resources/static/appcss/bootstrap-reboot.css.map
	git restore --staged     src/main/resources/static/appcss/bootstrap-reboot.min.css
	git restore --staged     src/main/resources/static/appcss/bootstrap-reboot.min.css.map
	git restore --staged     src/main/resources/static/appcss/bootstrap.css
	git restore --staged     src/main/resources/static/appcss/bootstrap.css.map
	git restore --staged     src/main/resources/static/appcss/bootstrap.min.css
	git restore --staged     src/main/resources/static/appcss/bootstrap.min.css.map
	git restore --staged     src/main/resources/static/appcss/daterange.css
	git restore --staged     src/main/resources/static/appcss/easy-wizard/jquery.snippet.min.css
	git restore --staged     src/main/resources/static/appcss/easy-wizard/styles.css
	git restore --staged     src/main/resources/static/appcss/fullcalendar.css
	git restore --staged     src/main/resources/static/appcss/gallery.css
	git restore --staged     src/main/resources/static/appcss/h
	git restore --staged     src/main/resources/static/appcss/login.css
	git restore --staged     src/main/resources/static/appcss/main.css
	git restore --staged     src/main/resources/static/appcss/main.scss
	git restore --staged     src/main/resources/static/appcss/slidebars.css
	git restore --staged     src/main/resources/static/appcss/summernote.css
	git restore --staged     src/main/resources/static/appcss/sweet-alert/ie9.css
	git restore --staged     src/main/resources/static/appcss/sweet-alert/notifications.css
	git restore --staged     src/main/resources/static/appcss/sweet-alert/sweet-alert.css
	git restore --staged     src/main/resources/static/assets/brand/bootstrap-outline.svg
	git restore --staged     src/main/resources/static/assets/brand/bootstrap-solid.svg
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap-grid.css
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap-grid.css.map
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap-grid.min.css
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap-grid.min.css.map
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap-reboot.css
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap-reboot.css.map
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap-reboot.min.css
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap-reboot.min.css.map
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap.css
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap.css.map
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap.min.css
	git restore --staged     src/main/resources/static/assets/dist/css/bootstrap.min.css.map
	git restore --staged     src/main/resources/static/assets/dist/js/bootstrap.bundle.js
	git restore --staged     src/main/resources/static/assets/dist/js/bootstrap.bundle.js.map
	git restore --staged     src/main/resources/static/assets/dist/js/bootstrap.bundle.min.js
	git restore --staged     src/main/resources/static/assets/dist/js/bootstrap.bundle.min.js.map
	git restore --staged     src/main/resources/static/assets/dist/js/bootstrap.js
	git restore --staged     src/main/resources/static/assets/dist/js/bootstrap.js.map
	git restore --staged     src/main/resources/static/assets/dist/js/bootstrap.min.js
	git restore --staged     src/main/resources/static/assets/dist/js/bootstrap.min.js.map
	git restore --staged     src/main/resources/static/css/.sass-cache/24c15b34655e5e1aa360598426e3f80f3ea65ba6/main.scssc
	git restore --staged     src/main/resources/static/css/.sass-cache/3a8ce4a57b74db98ea6b37ec0ca12d0a62a1ad5f/main.scssc
	git restore --staged     src/main/resources/static/css/.sass-cache/43109e1a82780fba88759401e0aeeff46679c391/main.scssc
	git restore --staged     src/main/resources/static/css/.sass-cache/703a848320218708384a8acbe165d795a68eca76/main-two.scssc
	git restore --staged     src/main/resources/static/css/.sass-cache/703a848320218708384a8acbe165d795a68eca76/main.scssc
	git restore --staged     src/main/resources/static/css/.sass-cache/82e08a38850f9c7423ca4660ef4b66c5184bfa55/main.scssc
	git restore --staged     src/main/resources/static/css/.sass-cache/afbebcd773a1d7011d548c0fe9074c3806dbc5dc/main.scssc
	git restore --staged     src/main/resources/static/css/album.css
	git restore --staged     src/main/resources/static/css/animate.css
	git restore --staged     src/main/resources/static/css/bootstrap.css
	git restore --staged     src/main/resources/static/css/bootstrap.min.css
	git restore --staged     src/main/resources/static/css/carousel.css
	git restore --staged     src/main/resources/static/css/cover.css
	git restore --staged     src/main/resources/static/css/dashboard.css
	git restore --staged     src/main/resources/static/css/daterange.css
	git restore --staged     src/main/resources/static/css/easy-wizard/jquery.snippet.min.css
	git restore --staged     src/main/resources/static/css/easy-wizard/styles.css
	git restore --staged     src/main/resources/static/css/fullcalendar.css
	git restore --staged     src/main/resources/static/css/gallery.css
	git restore --staged     src/main/resources/static/css/h
	git restore --staged     src/main/resources/static/css/login.css
	git restore --staged     src/main/resources/static/css/main.css
	git restore --staged     src/main/resources/static/css/main.scss
	git restore --staged     src/main/resources/static/css/slidebars.css
	git restore --staged     src/main/resources/static/css/summernote.css
	git restore --staged     src/main/resources/static/css/sweet-alert/ie9.css
	git restore --staged     src/main/resources/static/css/sweet-alert/notifications.css
	git restore --staged     src/main/resources/static/css/sweet-alert/sweet-alert.css
	git restore --staged     src/main/resources/static/favicon.ico
	git restore --staged     src/main/resources/static/flipcss/basic.css
	git restore --staged     src/main/resources/static/flipjs/basic.js
	git restore --staged     src/main/resources/static/flipjs/hash.js
	git restore --staged     src/main/resources/static/flipjs/jgestures.min.js
	git restore --staged     src/main/resources/static/flipjs/jquery-ui-1.8.20.custom.min.js
	git restore --staged     src/main/resources/static/flipjs/jquery.min.1.7.js
	git restore --staged     src/main/resources/static/flipjs/jquery.mousewheel.min.js
	git restore --staged     src/main/resources/static/flipjs/modernizr.2.5.3.min.js
	git restore --staged     src/main/resources/static/flipjs/scissor.js
	git restore --staged     src/main/resources/static/flipjs/scissor.min.js
	git restore --staged     src/main/resources/static/flipjs/turn.html4.js
	git restore --staged     src/main/resources/static/flipjs/turn.html4.min.js
	git restore --staged     src/main/resources/static/flipjs/turn.js
	git restore --staged     src/main/resources/static/flipjs/turn.min.js
	git restore --staged     src/main/resources/static/flipjs/zoom.js
	git restore --staged     src/main/resources/static/flipjs/zoom.min.js
	git restore --staged     src/main/resources/static/fonts/FontAwesome.otf
	git restore --staged     src/main/resources/static/fonts/Metrize-Icons.dev.svg
	git restore --staged     src/main/resources/static/fonts/Metrize-Icons.eot
	git restore --staged     src/main/resources/static/fonts/Metrize-Icons.svg
	git restore --staged     src/main/resources/static/fonts/Metrize-Icons.ttf
	git restore --staged     src/main/resources/static/fonts/Metrize-Icons.woff
	git restore --staged     src/main/resources/static/fonts/font-awesome.css
	git restore --staged     src/main/resources/static/fonts/font-awesome.min.css
	git restore --staged     src/main/resources/static/fonts/fontawesome-webfont.eot
	git restore --staged     src/main/resources/static/fonts/fontawesome-webfont.svg
	git restore --staged     src/main/resources/static/fonts/fontawesome-webfont.ttf
	git restore --staged     src/main/resources/static/fonts/fontawesome-webfont.woff
	git restore --staged     src/main/resources/static/fonts/fontawesome-webfont.woff2
	git restore --staged     src/main/resources/static/fonts/glyphicons-halflings-regular.eot
	git restore --staged     src/main/resources/static/fonts/glyphicons-halflings-regular.svg
	git restore --staged     src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
	git restore --staged     src/main/resources/static/fonts/glyphicons-halflings-regular.woff
	git restore --staged     src/main/resources/static/fonts/index.html
	git restore --staged     src/main/resources/static/fonts/metrize.css
	git restore --staged     src/main/resources/static/images/parallax1.jpeg
	git restore --staged     src/main/resources/static/js01/bootstrap.bundle.min.js
	git restore --staged     src/main/resources/static/js01/bootstrap.bundle.min.js.map
	git restore --staged     src/main/resources/static/js01/bootstrap.js
	git restore --staged     src/main/resources/static/js01/bootstrap.min.js
	git restore --staged     src/main/resources/static/js01/calendar/custom.js
	git restore --staged     src/main/resources/static/js01/calendar/fullcalendar.js
	git restore --staged     src/main/resources/static/js01/calendar/fullcalendar.min.js
	git restore --staged     src/main/resources/static/js01/custom-forms.js
	git restore --staged     src/main/resources/static/js01/custom-index-2.js
	git restore --staged     src/main/resources/static/js01/custom-index.js
	git restore --staged     src/main/resources/static/js01/custom-maps.js
	git restore --staged     src/main/resources/static/js01/custom.js
	git restore --staged     src/main/resources/static/js01/custom2.js
	git restore --staged     src/main/resources/static/js01/datepicker/jquery-ui.js
	git restore --staged     src/main/resources/static/js01/datepicker/ui.css
	git restore --staged     src/main/resources/static/js01/daterange/daterangepicker.js
	git restore --staged     src/main/resources/static/js01/daterange/moment.js
	git restore --staged     src/main/resources/static/js01/dist/bootstrap.bundle.js
	git restore --staged     src/main/resources/static/js01/dist/bootstrap.bundle.js.map
	git restore --staged     src/main/resources/static/js01/dist/bootstrap.bundle.min.js
	git restore --staged     src/main/resources/static/js01/dist/bootstrap.bundle.min.js.map
	git restore --staged     src/main/resources/static/js01/dist/bootstrap.js
	git restore --staged     src/main/resources/static/js01/dist/bootstrap.js.map
	git restore --staged     src/main/resources/static/js01/dist/bootstrap.min.js
	git restore --staged     src/main/resources/static/js01/dist/bootstrap.min.js.map
	git restore --staged     src/main/resources/static/js01/dist/dashboard.js
	git restore --staged     src/main/resources/static/js01/easy-wizard/jquery.easyWizard.js
	git restore --staged     src/main/resources/static/js01/easy-wizard/jquery.snippet.min.js
	git restore --staged     src/main/resources/static/js01/easy-wizard/scripts.js
	git restore --staged     src/main/resources/static/js01/flot/custom/area-chart.js
	git restore --staged     src/main/resources/static/js01/flot/custom/combine-chart-compare.js
	git restore --staged     src/main/resources/static/js01/flot/custom/combine-chart.js
	git restore --staged     src/main/resources/static/js01/flot/custom/crosshair.js
	git restore --staged     src/main/resources/static/js01/flot/custom/donut-pie-chart.js
	git restore --staged     src/main/resources/static/js01/flot/custom/horizontal-bar.js
	git restore --staged     src/main/resources/static/js01/flot/custom/interactive-pie-chart.js
	git restore --staged     src/main/resources/static/js01/flot/custom/pie-hide-label.js
	git restore --staged     src/main/resources/static/js01/flot/custom/rectangular-pie.js
	git restore --staged     src/main/resources/static/js01/flot/custom/stacked-bar-chart.js
	git restore --staged     src/main/resources/static/js01/flot/custom/toggle-series.js
	git restore --staged     src/main/resources/static/js01/flot/custom/vertical-bar.js
	git restore --staged     src/main/resources/static/js01/flot/custom/x-axis-grid.js
	git restore --staged     src/main/resources/static/js01/flot/custom/y-axis-grid.js
	git restore --staged     src/main/resources/static/js01/flot/custom/zoom.js
	git restore --staged     src/main/resources/static/js01/flot/flot.excanvas.min.js
	git restore --staged     src/main/resources/static/js01/flot/jquery.flot.axislabels.js
	git restore --staged     src/main/resources/static/js01/flot/jquery.flot.crosshair.js
	git restore --staged     src/main/resources/static/js01/flot/jquery.flot.js
	git restore --staged     src/main/resources/static/js01/flot/jquery.flot.pie.js
	git restore --staged     src/main/resources/static/js01/flot/jquery.flot.resize.js
	git restore --staged     src/main/resources/static/js01/flot/jquery.flot.selection.js
	git restore --staged     src/main/resources/static/js01/flot/jquery.flot.stack.js
	git restore --staged     src/main/resources/static/js01/flot/jquery.flot.time.js
	git restore --staged     src/main/resources/static/js01/flot/jquery.flot.tooltip.js
	git restore --staged     src/main/resources/static/js01/gallery/baguetteBox.js
	git restore --staged     src/main/resources/static/js01/gallery/plugins.js
	git restore --staged     src/main/resources/static/js01/google-api.js
	git restore --staged     src/main/resources/static/js01/html5shiv.js
	git restore --staged     src/main/resources/static/js01/jquery.datatables.js
	git restore --staged     src/main/resources/static/js01/jquery.js
	git restore --staged     src/main/resources/static/js01/jquery.ui.js
	git restore --staged     src/main/resources/static/js01/jqvmap/data/jquery.vmap.sampledata.js
	git restore --staged     src/main/resources/static/js01/jqvmap/jquery.vmap.js
	git restore --staged     src/main/resources/static/js01/jqvmap/jquery.vmap.min.js
	git restore --staged     src/main/resources/static/js01/jqvmap/jquery.vmap.packed.js
	git restore --staged     src/main/resources/static/js01/jqvmap/jqvmap.css
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/continents/jquery.vmap.africa.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/continents/jquery.vmap.asia.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/continents/jquery.vmap.australia.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/continents/jquery.vmap.europe.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/continents/jquery.vmap.north-america.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/continents/jquery.vmap.south-america.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/continents/readme.txt
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/jquery.vmap.europe.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/jquery.vmap.france.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/jquery.vmap.germany.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/jquery.vmap.russia.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/jquery.vmap.usa.js
	git restore --staged     src/main/resources/static/js01/jqvmap/maps/jquery.vmap.world.js
	git restore --staged     src/main/resources/static/js01/respond.min.js
	git restore --staged     src/main/resources/static/js01/slidebars.js
	git restore --staged     src/main/resources/static/js01/sparkline.js
	git restore --staged     src/main/resources/static/js01/summernote/summernote.js
	git restore --staged     src/main/resources/static/js01/summernote/summernote.min.js
	git restore --staged     src/main/resources/static/js01/sweet-alert/sweet-alert.js
	git restore --staged     src/main/resources/static/js01/sweet-alert/sweet-alert.min.js
	git restore --staged     src/main/resources/static/js01/tiny-scrollbar.js
	git restore --staged     src/main/resources/static/js01/wizard/bwizard.js
	git restore --staged     src/main/resources/static/js01/wizard/bwizard.min.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/bootstrap-wysihtml5.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.ar-AR.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.bg-BG.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.ca-CT.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.cs-CZ.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.de-DE.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.el-GR.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.es-AR.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.es-ES.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.fr-FR.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.hr-HR.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.it-IT.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.ja-JP.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.ko-KR.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.lt-LT.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.mo-MD.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.nb-NB.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.nl-NL.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.pl-PL.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.pt-BR.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.ru-RU.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.sk-SK.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.sv-SE.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.tr-TR.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.ua-UA.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.zh-CN.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/locales/bootstrap-wysihtml5.zh-TW.js
	git restore --staged     src/main/resources/static/js01/wysiwyg/wysihtml5-0.3.0.js

# Changes not staged for commit:
  # (use "git add <file>..." to update what will be committed)
  # (use "git restore <file>..." to discard changes in working directory)
	# modified:   .gitignore
	# modified:   src/main/java/com/evoltech/library/config/ApplicationStartup.java
	# modified:   src/main/java/com/evoltech/library/controller/AlumnoController.java
	# modified:   src/main/java/com/evoltech/library/service/ColeccionService.java
	# modified:   src/main/resources/templates/ADocumento.html
	# modified:   src/main/resources/templates/ADocumentos.html

# Untracked files:
  # (use "git add <file>..." to include in what will be committed)
	# .swp
	# unstage.sh

